### ISSUE TITLE
Update diagram

### ISSUE THREAD

**Issue by xhliu** [sCrypt-Inc/learn-scrypt-courses#15]
from ETH to Bitcoin. Or just remove ETH if it is easier.
![image](https://user-images.githubusercontent.com/1017252/187508562-34abc4d6-02a9-4870-9366-c08ad2849132.png)

https://learn.scrypt.io/en/courses/630b1fe6c26857959e13e160/lessons/1/chapters/3

**Comment by xhliu** [comment]
![image](https://user-images.githubusercontent.com/1017252/187513856-ec15ca98-e201-441a-99e9-44af6538c6a2.png)
https://learn.scrypt.io/en/courses/630b1fe6c26857959e13e160/lessons/2/chapters/1

**Comment by xhliu** [comment]
The code to complete is already shown:
![image](https://user-images.githubusercontent.com/1017252/187517653-d9905913-7549-4ebe-bd08-39d86285fa6f.png)

Use Bonus Update as the code to complete.
https://learn.scrypt.io/en/courses/630b1fe6c26857959e13e160/lessons/2/chapters/2

**Comment by xhliu** [comment]
![image](https://user-images.githubusercontent.com/1017252/187540331-a8067525-592a-46cf-8454-e6c5f6bfbe9b.png)
Move from https://learn.scrypt.io/en/courses/630b1fe6c26857959e13e160/lessons/3/chapters/1 to https://learn.scrypt.io/en/courses/630b1fe6c26857959e13e160/lessons/2/chapters/2

Put it around 

> After confirming the rules, the next important job is to determine the inputs and outputs of the circuit, which seems to be very straightforward:

**Comment by xhliu** [comment]
> The code to complete is already shown: ![image](https://user-images.githubusercontent.com/1017252/187517653-d9905913-7549-4ebe-bd08-39d86285fa6f.png)
> 

Not fixed yet.

**Comment by zhfnjust** [comment]
> > The code to complete is already shown: ![image](https://user-images.githubusercontent.com/1017252/187517653-d9905913-7549-4ebe-bd08-39d86285fa6f.png)
> 
> Not fixed yet.

fixed

**Comment by xhliu** [comment]
> ![image](https://user-images.githubusercontent.com/1017252/187540331-a8067525-592a-46cf-8454-e6c5f6bfbe9b.png) Move from https://learn.scrypt.io/en/courses/630b1fe6c26857959e13e160/lessons/3/chapters/1 to https://learn.scrypt.io/en/courses/630b1fe6c26857959e13e160/lessons/2/chapters/2
> 
> Put it around
> 
> > After confirming the rules, the next important job is to determine the inputs and outputs of the circuit, which seems to be very straightforward:

This and 
![image](https://user-images.githubusercontent.com/1017252/190209977-7aa93aef-787c-45d3-825a-abd591ed9bfe.png)

**Comment by zhfnjust** [comment]
Fixed
