### ISSUE TITLE
Change puzzle

### ISSUE THREAD

**Issue by xhliu** [sCrypt-Inc/learn-scrypt-courses#23]
since its solution is already shown. Or hide the solution. https://learn.scrypt.io/en/courses/Build-a-Tic-tac-toe-Game-with-sCrypt-614c387bc0974f55df5af1e5/lessons/2/chapters/2
![image](https://user-images.githubusercontent.com/1017252/218610745-d3c7553d-8aaf-4175-87d9-a98726754235.png)

**Comment by zhfnjust** [comment]
Fixed https://github.com/sCrypt-Inc/learn-scrypt-courses/commit/f48a431e7a932ae00e1ad6cfef447e9f91e28245
